language: node_js
node_js:
  - 8
install:
  # - npm install -g coveralls
  - npm install
script:
  - npm test # for normal testing
  # - npm run test-coverage && cat coverage/lcov.info | coveralls  # for coverage enabled testing
