language: node_js
node_js:
  - 12
install:
  - npm install -g coveralls
  - npm install -g @microsoft/rush
  - git clone --branch=backup https://github.com/captainheart/specron-framework.git ~/specron-framework
  - cd ..
  - mv ./specron-example ~/specron-framework/packages/
  - cd ~/specron-framework
  - rush update # or `rush install`
  - rush build
  - cd ./packages/specron-example
  # - export PATH=~/specron-framework/packages/specron-example/node_modules/@specron/cli/bin:$PATH
  - export PATH=~/specron-framework/packages/specron-cli/bin:$PATH
script:
  # - npm test # for normal testing
  - npm run test-coverage

after_success:
  - cat coverage/lcov.info | coveralls  # for coverage enabled testing
